#!/bin/bash

echo "Is it morning? Please answer yes or no"
read timeofday

case "$timeofday" in
    yes | y | Y | Yes | YES)    echo "Good Morning";;
    no | n | N | No | NO)       echo "Good Afternoon";;
    *)                          echo "Sorry, answer not recognized";;
esac

exit 0
